#' Create Flight Query
#'
#' Create a flight query object for use in \code{run} function
#'
#' This function uses a connection object to create a flight query object.
#' These can be manipulated using the \code{filter}, \code{select} and other
#' functions before passing to \code{run} to execute and return a dataframe.
#' This object won't work by itself - you will need to set a database, select elements
#' etc for it to work.
#'
#'  @param conn A connection object generated by \code{connect}
#'  @param ems_name A string, indicating the name of the EMS server
#'

#' @export
flt_query <-
  function(conn, ems_name, data_file=NULL)
  {
    obj <- list()
    class(obj) <- 'FltQuery'
    # Instantiating other objects
    obj$connection <- conn
    obj$ems        <- ems(conn)
    obj$ems_id     <- get_id(obj$ems, ems_name)
    obj$flight     <- flight(conn, obj$ems_id, data_file)

    # object data
    obj$queryset <- list()
    obj$columns  <- list()
    obj <- reset(obj)

    return(obj)
  }






