#' Generate Preset Fieldtree
#'
#' Initialize a \code{fltquery} object with available tree objects.
#'
#' This function will take the existing tree available in the object and
#' attempt to generate a fieldtree based on the available root paths in the object.
#' Typically this woule be the first call after initializing a \code{fltquery} object,
#' as calls to \code{update_fieldtree} or \code{select} may not even work until a
#' minimal fieldtree is available.
#'
#'  @param qry A fltquery object generated by \code{flt_query}
#'  @return A FltQuery object updated with fieldtree paths for use downstream.
#'
#' @examples
#' \dontrun{
#' conn <- connect("joe.bloggs", "mypassword")
#' qry <- flt_query(conn, "my-ems", data_file = "metadata.db")
#' qry <- generate_preset_fieldtree(qry)
#' }
#'
#' @export
#'
generate_preset_fieldtree <- function(qry) {
    qry$flight <- make_default_tree(qry$flight)
    return(qry)
  }
