#' Retrieve the names of EMS Instances
#'
#' Convenience function to check what EMS Names are available to your user
#'
#' The flt_query object requires a EMS name, but the ones available to you may not be immediately
#' obvious - this function retrieves those names.
#'
#' @param conn A connection object generated by \code{connect} with an active auth token
#' @return a string vector of the available EMS names for your user
#'
#'
#' @export

retrieve_ems_instances <- function(conn) {
  l <- ems(conn = conn)
  return(l$list$name)
}
